### ISSUE TITLE
Can you choose any style to run normally? 

### ISSUE THREAD

**Issue by zzzyn1** [USTC-Keyanjie/Android-Style-Transfer#1]
Can you choose any style to run normally? Why do I only choose la_muse style?
为什么我只有在选择la_muse风格的时候才可以得到正确的迁移结果，选择其他风格就会抛出异常？我看代码里la_muse的output_node单独处理了一下，这是为什么？其他风格无法正确迁移和这个有关吗？

**Comment by USTC-Keyanjie** [comment]
la_muse风格的模型不是我训练的，这个模型对于输入图片的尺寸要求是640*480*3，所以我再使用时需要预处理一下，其他的模型不需要。
如果能否详细说明抛出什么异常，手机会闪退吗。
我自己用的华为mate9，Android版本8.0是没有问题的。

**Comment by USTC-Keyanjie** [comment]
la_muse风格的模型不是我训练的，这个模型对于输入图片的尺寸要求是[640, 480, 3]，所以我再使用时需要预处理一下，其他的模型不需要。
如果能否详细说明抛出什么异常，手机会闪退吗。
我自己用的华为mate9，Android版本8.0是没有问题的。

**Comment by USTC-Keyanjie** [comment]
la_muse风格的模型不是我训练的，这个模型对于输入图片的尺寸要求是 640 x 480 x 3，所以我再使用时需要预处理一下，其他的模型不需要。
如果能否详细说明抛出什么异常，手机会闪退吗。
我自己用的华为mate9，Android版本8.0是没有问题的。

**Comment by USTC-Keyanjie** [comment]
la_muse风格的模型不是我训练的，这个模型输出节点的name和其他模型不一样，只是改了一个输出节点的名字，所以我再使用时需要预处理一下，其他的模型不需要。
如果能否详细说明抛出什么异常，手机会闪退吗。
我自己用的华为mate9，Android版本8.0是没有问题的。

**Comment by zzzyn1** [comment]
应该是手机的问题，我换了一个手机以后都可以正常运行了，可能是之前的手机比较旧了。另外不知道你方不方便分享一下风格迁移的python源代码呀，想要学习一下

**Comment by USTC-Keyanjie** [comment]
Python源代码也是我在github上找的别人的，没有自己写过，就不分享了，你在github上搜搜看吧。
