### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by ShaofengZou** [USTC-Keyanjie/Android-Style-Transfer#2]
你好呀：
       想问下除了la_muse风格的模型外，其他几个模型都是你训练的吗？可否分享下模型训练和转换的代码呀？
       期待你的回复！

**Comment by USTC-Keyanjie** [comment]
抱歉这么晚看到。
这几个模型都不是我自己训练的，也是从别人那里下载到的。
我自己尝试训练过，记得移植到手机端总有错误，大概是某种运算（可能是L2Loss）手机端不支持，最后放弃了。

**Comment by ShaofengZou** [comment]
^_^
我找到了解决办法。
https://github.com/GuidoPaul/Android-Tensorflow-Style-Transfer 里面有关于模型训练的部分，训练好的pb模型部署到安卓端的时候，有几处还需要修改：
1. input node and output node
2. input tensor size
3. normalize the output

**Comment by USTC-Keyanjie** [comment]
请问你成功了吗？
我之前也尝试过，但是没有成功。

**Comment by ShaofengZou** [comment]
嗯，成功啦，这两天我整理下，然后分享给你。

**Comment by USTC-Keyanjie** [comment]
非常非常感谢！

**Comment by ShaofengZou** [comment]
做了下整理，可以参考下~
https://github.com/ShaofengZou/Android-Style-Transfer.git

**Comment by USTC-Keyanjie** [comment]
点赞！
